[workspace]
changelog_update = true
dependencies_update = false
git_release_enable = false

[[package]]
name = "iwe"
git_release_enable = true
git_release_name = "v{{ version }}"
git_release_draft = false
changelog_update = true

[[package]]
name = "iwes"
git_release_enable = false
git_release_draft = false
changelog_update = true

[[package]]
name = "liwe"
git_release_enable = false
git_release_draft = false
changelog_update = true
